import type { EvidenceSource, Flashcard, QuizQuestion, Topic } from './types'

const pubmedSearch = (title: string) =>
  `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(title)}`

export const sources: Record<string, EvidenceSource> = {
  pkpd: {
    title: 'Pharmacokinetic and pharmacodynamic concepts as applied to the design of dose selection',
    journal: 'Clinical Pharmacokinetics',
    year: 2014,
    url: pubmedSearch('pharmacokinetic pharmacodynamic concepts dose selection'),
  },
  ace: {
    title: 'Angiotensin-converting enzyme inhibitors',
    journal: 'Circulation',
    year: 1998,
    url: pubmedSearch('Angiotensin-converting enzyme inhibitors Brown Vaughan Circulation'),
  },
  warfarin: {
    title: 'Pharmacogenetics of warfarin: current status and future challenges',
    journal: 'The Pharmacogenomics Journal',
    year: 2007,
    url: pubmedSearch('Pharmacogenetics of warfarin current status future challenges'),
  },
  aminoglycoside: {
    title: 'Aminoglycosides: nephrotoxicity',
    journal: 'Antimicrobial Agents and Chemotherapy',
    year: 1999,
    pmid: '10223907',
    url: 'https://pubmed.ncbi.nlm.nih.gov/10223907/',
  },
  metformin: {
    title: 'The mechanisms of action of metformin',
    journal: 'Diabetologia',
    year: 2017,
    url: pubmedSearch('The mechanisms of action of metformin Rena Hardie Pearson'),
  },
  sglt2: {
    title: 'Empagliflozin, Cardiovascular Outcomes, and Mortality in Type 2 Diabetes',
    journal: 'New England Journal of Medicine',
    year: 2015,
    pmid: '26378978',
    url: 'https://pubmed.ncbi.nlm.nih.gov/26378978/',
  },
  ppi: {
    title: 'Pharmacology of proton pump inhibitors',
    journal: 'Current Gastroenterology Reports',
    year: 2008,
    url: pubmedSearch('Pharmacology of proton pump inhibitors Shin Sachs'),
  },
  cyp: {
    title: 'Cytochrome P450 enzymes in drug metabolism: regulation of gene expression, enzyme activities, and impact of genetic variation',
    journal: 'Pharmacology & Therapeutics',
    year: 2013,
    url: pubmedSearch('Cytochrome P450 enzymes in drug metabolism Zanger Schwab'),
  },
  vancomycin: {
    title: 'Therapeutic monitoring of vancomycin for serious methicillin-resistant Staphylococcus aureus infections',
    journal: 'American Journal of Health-System Pharmacy',
    year: 2020,
    url: pubmedSearch('Therapeutic monitoring vancomycin serious MRSA infections 2020 consensus guideline'),
  },
  antidepressant: {
    title: 'Comparative efficacy and acceptability of 21 antidepressant drugs for the acute treatment of adults with major depressive disorder',
    journal: 'The Lancet',
    year: 2018,
    pmid: '29477251',
    url: 'https://pubmed.ncbi.nlm.nih.gov/29477251/',
  },
}

export const topics: Topic[] = [
  {
    id: 'pkpd',
    name: '약동학 · 약력학',
    englishName: 'PK · PD fundamentals',
    description: '농도–시간 곡선부터 용량 설계까지',
    icon: 'flask',
    tone: 'blue',
    mastery: 72,
    cardCount: 42,
    dueCount: 7,
    concepts: ['Clearance', 'Volume of distribution', 'Half-life', 'Bioavailability'],
    highYield: '반감기는 Vd와 CL의 비율로 결정됩니다.',
  },
  {
    id: 'cardio',
    name: '심혈관계 약물',
    englishName: 'Cardiovascular pharmacology',
    description: '혈압·심부전·항응고 치료의 연결 구조',
    icon: 'heart',
    tone: 'coral',
    mastery: 64,
    cardCount: 58,
    dueCount: 9,
    concepts: ['RAAS', 'β-blockers', 'Anticoagulants', 'Diuretics'],
    highYield: 'RAAS 차단은 적응증과 금기를 함께 묶어 기억하세요.',
  },
  {
    id: 'infectious',
    name: '감염 약물치료',
    englishName: 'Infectious diseases',
    description: '작용기전·항균 스펙트럼·내성의 삼각형',
    icon: 'shield',
    tone: 'sage',
    mastery: 48,
    cardCount: 66,
    dueCount: 12,
    concepts: ['Cell wall', 'Protein synthesis', 'Resistance', 'PK/PD targets'],
    highYield: '항생제는 표적–스펙트럼–독성을 한 세트로 회상하세요.',
  },
  {
    id: 'endocrine',
    name: '내분비계 약물',
    englishName: 'Endocrine pharmacology',
    description: '당뇨·갑상선·스테로이드의 핵심 원리',
    icon: 'droplet',
    tone: 'teal',
    mastery: 81,
    cardCount: 47,
    dueCount: 4,
    concepts: ['Insulin', 'Incretins', 'SGLT2', 'Thyroid axis'],
    highYield: '혈당강하제는 장기 이득과 이상반응을 함께 비교하세요.',
  },
  {
    id: 'cns',
    name: '중추신경계 약물',
    englishName: 'Neuropharmacology',
    description: '신경전달물질 회로와 임상 효과 연결',
    icon: 'brain',
    tone: 'plum',
    mastery: 56,
    cardCount: 61,
    dueCount: 8,
    concepts: ['Monoamines', 'GABA', 'Dopamine', 'Seizure pathways'],
    highYield: '수용체 작용을 효과·이상반응과 같은 회로에 놓으세요.',
  },
  {
    id: 'gi',
    name: '소화기계 약물',
    englishName: 'Gastrointestinal pharmacology',
    description: '산 분비·운동성·구토 조절의 기전',
    icon: 'pill',
    tone: 'amber',
    mastery: 76,
    cardCount: 34,
    dueCount: 3,
    concepts: ['Acid suppression', 'Motility', 'Antiemetics', 'IBD therapy'],
    highYield: 'PPI는 활성화 장소와 투여 시점을 연결해 기억하세요.',
  },
  {
    id: 'oncology',
    name: '항암 약물치료',
    englishName: 'Oncology therapeutics',
    description: '세포주기·표적치료·면역치료를 한눈에',
    icon: 'target',
    tone: 'plum',
    mastery: 31,
    cardCount: 53,
    dueCount: 6,
    concepts: ['Cell cycle', 'Kinase inhibitors', 'Immunotherapy', 'Supportive care'],
    highYield: '표적 단백질과 예측 가능한 독성을 짝지어 학습하세요.',
  },
  {
    id: 'safety',
    name: '상호작용 · 안전성',
    englishName: 'Interactions · safety',
    description: 'CYP·금기·모니터링을 실전 처방처럼',
    icon: 'alert',
    tone: 'amber',
    mastery: 43,
    cardCount: 39,
    dueCount: 10,
    concepts: ['CYP enzymes', 'QT prolongation', 'Renal dosing', 'TDM'],
    highYield: '상호작용은 perpetrator와 victim drug를 구분하세요.',
  },
]

export const flashcards: Flashcard[] = [
  {
    id: 'pk-01', topicId: 'pkpd', difficulty: 1,
    front: '반감기(t½)를 청소율(CL)과 분포용적(Vd)으로 표현하면?',
    back: 't½ = 0.693 × Vd / CL',
    pearl: 'CL이 감소하거나 Vd가 증가하면 반감기가 길어집니다. 선형·1구획 가정에서의 핵심 관계입니다.',
    tags: ['half-life', 'equation'], source: sources.pkpd,
  },
  {
    id: 'pk-02', topicId: 'pkpd', difficulty: 2,
    front: '목표 혈중농도에 빠르게 도달하기 위한 부하용량(loading dose)의 결정식은?',
    back: 'Loading dose = 목표농도 × Vd / F',
    pearl: '부하용량은 주로 Vd와 생체이용률에 좌우됩니다. 신기능 저하는 대개 유지용량 조정에 더 직접적으로 반영됩니다.',
    tags: ['loading dose', 'bioavailability'], source: sources.pkpd,
  },
  {
    id: 'pk-03', topicId: 'pkpd', difficulty: 1,
    front: '선형 약동학에서 정상상태(steady state)에 도달하는 시간은 무엇이 결정하는가?',
    back: '약물의 반감기. 보통 4–5 반감기 후 정상상태의 약 94–97%에 도달합니다.',
    pearl: '용량을 늘리면 정상상태 농도는 높아지지만, 도달 시간은 바뀌지 않습니다.',
    tags: ['steady state', 'half-life'], source: sources.pkpd,
  },
  {
    id: 'cv-01', topicId: 'cardio', difficulty: 2,
    front: 'ACE 억제제가 마른기침을 유발하는 기전은?',
    back: 'ACE가 분해하던 bradykinin과 substance P가 축적되기 때문입니다.',
    pearl: 'Angiotensin II 감소뿐 아니라 bradykinin 증가가 ACE 억제제의 효과와 이상반응을 함께 설명합니다.',
    tags: ['ACE inhibitor', 'bradykinin'], source: sources.ace,
  },
  {
    id: 'cv-02', topicId: 'cardio', difficulty: 2,
    front: 'Warfarin이 억제하는 표적과 감소하는 응고인자는?',
    back: 'VKORC1을 억제하여 비타민 K 의존성 인자 II, VII, IX, X와 protein C/S의 활성화를 감소시킵니다.',
    pearl: 'Protein C의 반감기가 짧아 치료 초기에 일시적 과응고 상태가 생길 수 있습니다.',
    tags: ['warfarin', 'coagulation'], source: sources.warfarin,
  },
  {
    id: 'id-01', topicId: 'infectious', difficulty: 2,
    front: 'Aminoglycoside의 항균 효과를 예측하는 대표 PK/PD 지표는?',
    back: 'Cmax/MIC. 농도 의존적 살균과 post-antibiotic effect를 보입니다.',
    pearl: '높은 peak를 확보하면서 독성을 줄이기 위해 연장 간격 투여가 사용됩니다.',
    tags: ['aminoglycoside', 'PK/PD'], source: sources.aminoglycoside,
  },
  {
    id: 'id-02', topicId: 'infectious', difficulty: 3,
    front: 'Aminoglycoside가 혐기성균에 효과가 낮은 핵심 이유는?',
    back: '세균 내 유입에 산소 의존적 능동수송이 필요하기 때문입니다.',
    pearl: '세포벽 합성 억제제와의 병용은 세포 내 유입을 증가시켜 상승작용을 만들 수 있습니다.',
    tags: ['aminoglycoside', 'spectrum'], source: sources.aminoglycoside,
  },
  {
    id: 'en-01', topicId: 'endocrine', difficulty: 1,
    front: 'Metformin의 중심 혈당강하 기전은?',
    back: '간의 포도당 생성을 억제하고 말초 인슐린 감수성을 개선합니다.',
    pearl: '인슐린 분비를 직접 촉진하지 않아 단독 사용 시 저혈당 위험이 낮습니다.',
    tags: ['metformin', 'diabetes'], source: sources.metformin,
  },
  {
    id: 'en-02', topicId: 'endocrine', difficulty: 2,
    front: 'SGLT2 억제제가 혈당을 낮추는 신장 수준의 기전은?',
    back: '근위세뇨관에서 포도당·나트륨 재흡수를 억제하여 요당 배설을 증가시킵니다.',
    pearl: '심부전·신장 보호 이득과 함께 생식기 진균감염, 체액 감소, 정상혈당 케톤산증 위험을 연결해 기억하세요.',
    tags: ['SGLT2', 'renal'], source: sources.sglt2,
  },
  {
    id: 'gi-01', topicId: 'gi', difficulty: 2,
    front: 'Proton pump inhibitor가 식전 투여되는 이유는?',
    back: '식사로 활성화되는 proton pump가 많을 때, 산성 분비세관에서 활성화된 약물이 H⁺/K⁺-ATPase를 비가역적으로 억제하도록 하기 위해서입니다.',
    pearl: 'PPI는 산에 불안정한 prodrug이며 활성화된 펌프에 결합합니다.',
    tags: ['PPI', 'administration'], source: sources.ppi,
  },
  {
    id: 'sf-01', topicId: 'safety', difficulty: 2,
    front: 'Rifampin과 clarithromycin은 CYP3A4에 각각 어떤 영향을 주는가?',
    back: 'Rifampin은 강력한 inducer, clarithromycin은 inhibitor입니다.',
    pearl: '유도는 효소 발현에 시간이 필요하고 중단 후에도 효과가 지속될 수 있지만, 억제는 대체로 더 빠르게 나타납니다.',
    tags: ['CYP3A4', 'interaction'], source: sources.cyp,
  },
  {
    id: 'sf-02', topicId: 'safety', difficulty: 3,
    front: '중증 MRSA 감염에서 vancomycin 노출의 권장 AUC₍24₎/MIC 범위는? (MIC 1 mg/L 가정)',
    back: '400–600 mg·h/L',
    pearl: 'AUC 기반 모니터링은 유효 노출을 유지하면서 신독성 위험을 낮추는 것을 목표로 합니다.',
    tags: ['vancomycin', 'TDM'], source: sources.vancomycin,
  },
]

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'q-pk-01', topicId: 'pkpd', mode: 'calculation', eyebrow: '약동학 계산',
    question: 'Vd 40 L, CL 4 L/h인 약물의 예상 반감기는?',
    options: ['약 3.5시간', '약 6.9시간', '약 10시간', '약 27.7시간'],
    correctIndex: 1,
    explanation: 't½ = 0.693 × 40 / 4 = 6.93시간입니다.',
    takeaway: '반감기는 Vd/CL의 비율에 비례합니다.', source: sources.pkpd,
  },
  {
    id: 'q-pk-02', topicId: 'pkpd', mode: 'clinical', eyebrow: '신기능 저하 환자',
    question: '신기능 저하로 약물의 CL이 절반으로 감소했고 Vd는 변하지 않았습니다. 가장 적절한 설명은?',
    options: ['부하용량은 반드시 절반으로 줄인다', '반감기는 약 2배로 늘어난다', '정상상태 도달 시간은 짧아진다', '생체이용률은 자동으로 절반이 된다'],
    correctIndex: 1,
    explanation: 't½ = 0.693 × Vd/CL이므로 CL이 절반이면 반감기는 약 2배가 됩니다. 부하용량은 주로 Vd와 F로 결정됩니다.',
    takeaway: '신기능 변화는 유지용량과 투여 간격에 먼저 반영합니다.', source: sources.pkpd,
  },
  {
    id: 'q-cv-01', topicId: 'cardio', mode: 'clinical', eyebrow: '외래 처방 검토',
    question: 'Lisinopril 시작 후 지속적인 마른기침이 생겼습니다. 가장 직접적인 매개물질은?',
    options: ['Aldosterone', 'Bradykinin', 'Renin', 'Endothelin-1'],
    correctIndex: 1,
    explanation: 'ACE는 bradykinin을 분해합니다. ACE 억제 시 bradykinin이 축적되어 마른기침과 혈관부종에 관여합니다.',
    takeaway: 'ACE inhibitor: Ang II ↓ + bradykinin ↑', source: sources.ace,
  },
  {
    id: 'q-id-01', topicId: 'infectious', mode: 'core', eyebrow: '항균제 기전',
    question: 'Aminoglycoside의 효과와 가장 잘 연결되는 지표는?',
    options: ['Time above MIC', 'AUC/MIC만', 'Cmax/MIC', '최저농도/단백결합률'],
    correctIndex: 2,
    explanation: 'Aminoglycoside는 농도 의존적 살균을 나타내므로 peak와 MIC의 비율인 Cmax/MIC가 핵심 지표입니다.',
    takeaway: '높은 peak, 낮은 trough를 목표로 생각하세요.', source: sources.aminoglycoside,
  },
  {
    id: 'q-en-01', topicId: 'endocrine', mode: 'clinical', eyebrow: '당뇨 약료',
    question: 'SGLT2 억제제 복용 환자가 수술 전 금식 중 오심과 복통을 호소합니다. 혈당은 180 mg/dL입니다. 우선 의심할 것은?',
    options: ['젖산산증만', '정상혈당 케톤산증', '중증 저혈당', '갑상선 폭풍'],
    correctIndex: 1,
    explanation: 'SGLT2 억제제는 혈당이 매우 높지 않아도 케톤산증을 일으킬 수 있으며, 금식·수술·급성질환이 위험을 높입니다.',
    takeaway: '정상에 가까운 혈당이 ketoacidosis를 배제하지 않습니다.', source: sources.sglt2,
  },
  {
    id: 'q-gi-01', topicId: 'gi', mode: 'core', eyebrow: '복약지도',
    question: 'Omeprazole의 효과를 최적화하는 일반적인 복용 시점은?',
    options: ['취침 직전 식사와 무관하게', '식사 30–60분 전', '식후 즉시', '제산제와 반드시 동시에'],
    correctIndex: 1,
    explanation: '식전에 복용하면 약물이 흡수된 뒤 식사로 활성화된 proton pump를 효과적으로 억제할 수 있습니다.',
    takeaway: 'PPI의 prodrug 활성화와 식사 유발 펌프 활성화를 연결하세요.', source: sources.ppi,
  },
  {
    id: 'q-sf-01', topicId: 'safety', mode: 'clinical', eyebrow: '상호작용',
    question: 'CYP3A4로 주로 대사되는 약물에 rifampin을 병용하면 가장 예상되는 변화는?',
    options: ['기질 약물의 노출 증가', '기질 약물의 노출 감소', '즉각적인 신배설 중단', '단백결합률이 항상 100%가 됨'],
    correctIndex: 1,
    explanation: 'Rifampin은 CYP3A4와 여러 운반체를 유도해 기질 약물의 대사·배출을 증가시키고 노출을 낮출 수 있습니다.',
    takeaway: 'Inducer는 대개 victim drug의 농도를 낮춥니다.', source: sources.cyp,
  },
  {
    id: 'q-sf-02', topicId: 'safety', mode: 'calculation', eyebrow: 'TDM',
    question: '중증 MRSA 감염에서 vancomycin AUC₍24₎가 720 mg·h/L이고 MIC가 1 mg/L입니다. 가장 적절한 해석은?',
    options: ['목표보다 낮다', '권장 범위 안이다', '권장 범위보다 높아 신독성 위험을 재평가한다', 'MIC와 무관하므로 해석할 수 없다'],
    correctIndex: 2,
    explanation: '일반적인 권장 AUC₍24₎/MIC 목표는 400–600입니다. 720은 목표보다 높아 용량·간격과 신기능을 재평가합니다.',
    takeaway: 'Vancomycin은 trough 단독보다 AUC 기반 노출 평가를 우선합니다.', source: sources.vancomycin,
  },
]

export const conceptLinks: Record<string, { label: string; detail: string }[]> = {
  pkpd: [
    { label: 'Dose', detail: '투여량과 투여간격' },
    { label: 'Concentration', detail: '흡수·분포·대사·배설' },
    { label: 'Target engagement', detail: '수용체 결합과 신호 전달' },
    { label: 'Clinical effect', detail: '효과·독성·개인차' },
  ],
  cardio: [
    { label: 'RAAS', detail: '혈압·체액 항상성' },
    { label: 'Preload / Afterload', detail: '심실 부담 변화' },
    { label: 'Remodeling', detail: '장기 예후와 구조 변화' },
    { label: 'Outcomes', detail: '입원·사망·출혈' },
  ],
  infectious: [
    { label: 'Pathogen', detail: '균종·감염 부위' },
    { label: 'Drug exposure', detail: 'fT>MIC · Cmax/MIC · AUC/MIC' },
    { label: 'Kill pattern', detail: '시간·농도 의존성' },
    { label: 'Resistance', detail: '표적 변화·효소·유출' },
  ],
  endocrine: [
    { label: 'Hormone axis', detail: '분비와 음성 되먹임' },
    { label: 'Metabolic target', detail: '간·근육·지방·신장' },
    { label: 'Drug action', detail: '분비·감수성·배설' },
    { label: 'Organ benefit', detail: '심장·신장 장기 결과' },
  ],
  cns: [
    { label: 'Circuit', detail: '증상과 관련된 신경 회로' },
    { label: 'Transmitter', detail: '5-HT · DA · NE · GABA' },
    { label: 'Receptor', detail: '작용제·길항제·재흡수' },
    { label: 'Adaptation', detail: '효과 지연·내성·금단' },
  ],
  gi: [
    { label: 'Stimulus', detail: '식사·히스타민·가스트린' },
    { label: 'Effector', detail: '산 분비·운동·분비' },
    { label: 'Target', detail: '펌프·수용체·채널' },
    { label: 'Timing', detail: '식사·증상과 투여 시점' },
  ],
  oncology: [
    { label: 'Driver', detail: '유전자·수용체·경로' },
    { label: 'Targeted drug', detail: '선택적 경로 차단' },
    { label: 'Resistance', detail: '우회 신호·표적 변이' },
    { label: 'Biomarker', detail: '반응 예측·모니터링' },
  ],
  safety: [
    { label: 'Perpetrator', detail: '효소·운반체 변화 유발약' },
    { label: 'Pathway', detail: 'CYP · P-gp · 신배설' },
    { label: 'Victim', detail: '노출이 변하는 기질약' },
    { label: 'Action', detail: '회피·감량·모니터링' },
  ],
}
